import SwiftUI

struct ChatMessage: Identifiable {
    let id = UUID()
    let text: String
    let isUser: Bool
    // Optional list of recommendations to display as interactive cards
    var recommendations: [Recommendation]? = nil
}

struct AIChatView: View {
    @ObservedObject var recVM: RecommendationViewModel
    @Binding var isPresented: Bool
    
    @State private var messageText = ""
    @State private var messages: [ChatMessage] = [
        ChatMessage(text: "Hello! Tell me what you need (e.g., 'EV spot', 'Wide spot'). I'll search all lots for you.", isUser: false)
    ]
    
    var body: some View {
        NavigationView {
            VStack {
                ScrollViewReader { proxy in
                    ScrollView {
                        VStack(alignment: .leading, spacing: 15) {
                            ForEach(messages) { msg in
                                ChatBubble(message: msg) { selectedRec in
                                    handleRecommendationSelection(selectedRec)
                                }
                            }
                            
                            if recVM.isLoading {
                                HStack {
                                    ProgressView()
                                    Text("Searching all parking lots...")
                                        .font(.caption)
                                        .foregroundColor(.gray)
                                }
                                .padding(.leading)
                            }
                        }
                        .padding()
                    }
                    // Fix: iOS 17+ compatible onChange
                    .onChange(of: messages.count) { oldValue, newValue in
                        if let lastId = messages.last?.id {
                            withAnimation {
                                proxy.scrollTo(lastId, anchor: .bottom)
                            }
                        }
                    }
                }
                
                // Input Area
                HStack {
                    TextField("Type your request...", text: $messageText)
                        .padding()
                        .background(Color(UIColor.systemGray6))
                        .cornerRadius(20)
                        .disabled(recVM.isLoading)
                    
                    Button(action: sendMessage) {
                        Image(systemName: "paperplane.fill")
                            .font(.title2)
                            .foregroundColor(recVM.isLoading ? .gray : .blue)
                    }
                    .disabled(recVM.isLoading || messageText.isEmpty)
                }
                .padding()
            }
            .navigationTitle("AI Parking Assistant")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Close") {
                        recVM.shouldNavigate = false
                        isPresented = false
                    }
                }
            }
        }
    }
    
    func sendMessage() {
        let query = messageText
        messageText = ""
        
        messages.append(ChatMessage(text: query, isUser: true))
        
        Task {
            await recVM.getNLPRecommendation(query: query)
            
            // Create response message
            var responseText = recVM.aiResponseReason ?? "I'm sorry, I couldn't find anything."
            
            // If we have recommendations, we'll attach them to the message
            // (Limit to top 3 to match the text summary logic)
            let recs = Array(recVM.recommendations.prefix(3))
            
            // Clean up the text if it was generated by the VM to avoid duplication or adjust it
            // The VM generates a text summary list. We might want to keep that or simplify it.
            // For now, we'll keep the text as the "intro" and show buttons below.
            
            let responseMsg = ChatMessage(
                text: responseText,
                isUser: false,
                recommendations: recs.isEmpty ? nil : recs
            )
            
            messages.append(responseMsg)
        }
    }
    
    func formatLotIdForNavigation(_ lotID: String) -> String {
        // Standardizes lot IDs like "LotB", "lot b", "Lot_B" to "lot_b"
        let cleaned = lotID.lowercased().replacingOccurrences(of: " ", with: "").replacingOccurrences(of: "_", with: "")
        if cleaned.hasPrefix("lot"), let lastChar = cleaned.last, lastChar.isLetter {
            return "lot_\(lastChar)"
        }
        // Fallback for safety, though the above should handle all expected cases
        return lotID
    }

    func handleRecommendationSelection(_ rec: Recommendation) {
        print("--- DEBUG: Recommendation Tapped ---")
        print("Original Lot ID: \(rec.lotId)")
        print("Stall ID: \(rec.stallId)")

        let formattedId = formatLotIdForNavigation(rec.lotId)
        recVM.recommendedLotID = formattedId
        print("Formatted Lot ID for nav: \(formattedId)")
        
        recVM.recommendedStallID = rec.stallId
        recVM.shouldNavigate = true
        
        print("recVM.shouldNavigate set to: \(recVM.shouldNavigate)")
        print("------------------------------------")
        
        isPresented = false
    }
}

// MARK: - Helper Views

struct ChatBubble: View {
    let message: ChatMessage
    var onSelectRecommendation: ((Recommendation) -> Void)? = nil
    
    var body: some View {
        HStack(alignment: .top) {
            if message.isUser {
                Spacer()
                Text(message.text)
                    .padding()
                    .background(Color.blue)
                    .foregroundColor(.white)
                    .cornerRadius(15)
            } else {
                Image(systemName: "sparkle")
                    .font(.title2)
                    .foregroundColor(.blue)
                    .padding(.top, 5)
                
                VStack(alignment: .leading, spacing: 10) {
                    // The Text Response
                    Text(LocalizedStringKey(message.text))
                        .padding()
                        .background(Color(UIColor.systemGray6))
                        .cornerRadius(15)
                        .fixedSize(horizontal: false, vertical: true)
                    
                    // The Interactive Buttons (if any)
                    if let recs = message.recommendations, !recs.isEmpty {
                        ScrollView(.horizontal, showsIndicators: false) {
                            HStack(spacing: 15) {
                                ForEach(recs) { rec in
                                    VStack(alignment: .leading) {
                                        Text(formatLotName(rec.lotId))
                                            .font(.headline)
                                            .foregroundColor(.primary)
                                        Text("Spot \(rec.stallId.suffix(3))")
                                            .font(.subheadline)
                                            .foregroundColor(.secondary)
                                        Spacer()
                                        HStack {
                                            Spacer()
                                            Image(systemName: "chevron.right.circle.fill")
                                                .font(.title)
                                                .foregroundColor(.blue)
                                        }
                                    }
                                    .padding()
                                    .frame(width: 160, height: 120)
                                    .background(Color(UIColor.systemBackground))
                                    .cornerRadius(12)
                                    .shadow(color: Color.black.opacity(0.1), radius: 5, y: 2)
                                    .overlay(
                                        RoundedRectangle(cornerRadius: 12)
                                            .stroke(Color.blue.opacity(0.5), lineWidth: 1)
                                    )
                                    .contentShape(Rectangle())
                                    .onTapGesture {
                                        onSelectRecommendation?(rec)
                                    }
                                }
                            }
                            .padding(.vertical, 5)
                        }
                    }
                }
                Spacer()
            }
        }
    }
    
    func formatLotName(_ lotID: String) -> String {
        var niceName = lotID.replacingOccurrences(of: "_", with: " ").capitalized
        // Specific fix for "Lotb" -> "Lot B"
        if niceName.lowercased().hasPrefix("lot") && !niceName.contains(" ") && niceName.count > 3 {
            let index = niceName.index(niceName.startIndex, offsetBy: 3)
            niceName.insert(" ", at: index)
        }
        return niceName
    }
}
